name: nova-dso-tracker
services:
  nova:
    image: mrantonsg/nova-dso-tracker:5.0.0
    container_name: big-bear-nova-dso-tracker
    ports:
      - "5001:5001"
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
    network_mode: bridge
