name: nova-dso-tracker
services:
  nova:
    container_name: big-bear-nova-dso-tracker
    image: mrantonsg/nova-dso-tracker:5.0.0
    restart: unless-stopped
    networks:
      - big-bear-nova-dso-tracker
    ports:
      - 5001:5001
    volumes:
      - /DATA/AppData/nova-dso-tracker/instance:/app/instance
    x-casaos:
      ports:
        - container: "5001"
          description:
            en_us: Web Interface Port
      volumes:
        - container: /app/instance
          description:
            en_us: Database and instance storage directory.

networks:
  big-bear-nova-dso-tracker:
    driver: bridge

x-casaos:
  architectures:
    - amd64
    - arm64
  main: nova
  description:
    en_us: Nova DSO Tracker is a tool for astrophotographers to track Deep Space Objects, check observability, and manage imaging sessions.
  tagline:
    en_us: Real-time tracking and planning for Deep Space Objects.
  developer: mrantonSG
  author: mrantonSG
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/nova-dso-tracker/logo.png
  title:
    en_us: Nova DSO Tracker
  index: /
  port_map: "5001"
  scheme: http
  project_url: https://nova-tracker.com
```
